# Generated by Django 3.2.4 on 2021-07-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_indexofthirdheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='video/%y')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
