# Generated by Django 3.2.4 on 2021-07-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_mainvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexOfFourthHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='indexofsecondheading',
            name='heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='indexofthirdheading',
            name='heading',
            field=models.CharField(max_length=50),
        ),
    ]
