# Generated by Django 3.2.4 on 2021-07-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210702_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexOfCommunityHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/')),
                ('raisedcommunity', models.CharField(max_length=500)),
                ('heading', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
