# Generated by Django 3.2.4 on 2021-07-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_indexofcommunityhelp'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexofcommunityhelp',
            name='date',
            field=models.CharField(default='Date & Day', max_length=100),
        ),
    ]
