# Generated by Django 3.2.4 on 2021-07-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_indexofcommunityhelp_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexReviewsHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('sponsorname', models.CharField(max_length=100)),
            ],
        ),
    ]
