# Generated by Django 3.2.4 on 2021-07-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_donatefirstheading_donatesecheading_donatethirdheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateBigImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
