# Generated by Django 3.2.4 on 2021-07-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_donatebigimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('emai', models.CharField(max_length=500)),
            ],
        ),
    ]
