# Generated by Django 3.2.4 on 2021-07-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_emai_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
