# Generated by Django 3.2.4 on 2021-07-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_scheadingeight_scheadingfive_scheadingfour_scheadingone_scheadingseven_scheadingsix_scheadingthree_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheadingeight',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheadingfive',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheadingfour',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheadingone',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheadingseven',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheadingsix',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheadingthree',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheadingtwo',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
