# Generated by Django 3.2.4 on 2021-07-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_scmheadingfour_scmheadingone_scmheadingthree_scmheadingtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSHeadingOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
