# Generated by Django 3.2.4 on 2021-07-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_hunheadingfour_hunheadingone_hunheadingthree_hunheadingtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWHeadingFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=1000)),
                ('description2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PWHeadingFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PWHeadingOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=1000)),
                ('description2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PWHeadingSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=1000)),
                ('description2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PWHeadingSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PWHeadingThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=1000)),
                ('description2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PWHeadingTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
