# Generated by Django 3.2.4 on 2021-07-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_pwheadingfive_pwheadingfour_pwheadingone_pwheadingseven_pwheadingsix_pwheadingthree_pwheadingtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWBottomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post/')),
            ],
        ),
        migrations.CreateModel(
            name='PWMidImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post/')),
            ],
        ),
    ]
