# Generated by Django 3.2.4 on 2021-07-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_ssheadingfour_ssheadingone_ssheadingthree_ssheadingtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post/')),
            ],
        ),
    ]
