# Generated by Django 3.2.4 on 2021-07-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_rcheadingone_rcheadingtwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcheadingtwo',
            name='link',
        ),
        migrations.RemoveField(
            model_name='ttheadingtwo',
            name='link',
        ),
    ]
